version: '3.9'

services:
  movie-db:
    image: postgres:15
    environment:
      POSTGRES_DB: movieapp-db
      POSTGRES_USER: dev@movieapp
      POSTGRES_PASSWORD: password@movieapp
    volumes:
      - movieapp-db-data:/var/lib/postgresql/data
    networks:
      - movieapp-network
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 3s


volumes:
  movieapp-db-data:


networks:
  movieapp-network:
    driver: bridge
