server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: movieapp
  datasource:
    url: jdbc:postgresql://localhost:5433/movieapp
    username: dev@movieapp
    password: password@movieapp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: db/migrations/changelog-master.xml
    enabled: true
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
